### ISSUE TITLE
cmake config. error

### ISSUE THREAD

**Issue by Caglarr** [karel/gr-adapt#12]
Hi dear sir, I downloaded gr-adapt-main-3.9 branch also using gnuradio 3.9 and currently using cmake version 3.8 as mentioned in the readme. I tried to get cmake .. but there is an errors occured like shown below,

CMake Error at /usr/local/share/cmake-3.8/Modules/CMakeFindDependencyMacro.cmake:35 (message):
  Invalid arguments to find_dependency
![Screenshot from 2022-01-08 15-44-14](https://user-images.githubusercontent.com/33661779/148644673-b7d7b503-cf41-4ab2-bb4a-0d1b5cd9af46.png)

Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/gnuradio/GnuradioConfig.cmake:33 (find_dependency)
  CMakeLists.txt:76 (find_package)

Full output of the error is in the attachement. 
Would you mind give me an advice to solve this issue. 

Thanks in advance.
Best regards.

**Comment by karel** [comment]
Please make sure that all the GNU Radio dependencies are installed on your system. Although these are not explicitly listed as dependencies of gr-adapt, they are actually required, since building anything related to GNU Radio depends on them.
https://wiki.gnuradio.org/index.php/UbuntuInstall#Install_Dependencies

Line 33 in GnuradioConfig might be caused by missing libboost. If that's the case, then installing the dependencies listed in the link above should fix the situation.
https://github.com/gnuradio/gnuradio/blob/6aefb623fb368137e3eb3b92db4e4134627dd8d0/cmake/Modules/GnuradioConfig.cmake.in#L33

**Comment by Caglarr** [comment]
Hello Dear Karel, 
I checked many times dependency packets whether if install. It seems I installed all packets that the project needs. However I still couldn't build the project. Btw I installed cmake 3.8 
![Screenshot from 2022-01-17 22-32-06](https://user-images.githubusercontent.com/33661779/149827895-cb289e5b-2598-41df-88f7-992d49486ace.png)

Here is my CMakeError.log may be its helpful to find what my problem is. 
[CMakeError.log](https://github.com/karel/gr-adapt/files/7884276/CMakeError.log)

That's very important for me so a little help would be greatly appreciated.

**Comment by karel** [comment]
CMake 3.8 is the minimum version supported by GNU Radio ([see here](https://github.com/gnuradio/gnuradio/blob/3d4d9a4245b9e126d7119a7c81905c0d5423233b/CMakeLists.txt#L18)). Try the latest > 3.8 CMake that your Linux distribution provides. For example, the test system here uses 3.22.1.

**Comment by Caglarr** [comment]
Hello Karel, thanks for your help. I uninstalled cmake 3.8 version then install default cmake version from ubuntu 20.04 so problem is solved. Have a good day.
