### ISSUE TITLE
Throughput is reduced with libarmadillo

### ISSUE THREAD

**Issue by ashtum** [karel/gr-adapt#2]
Hi,
I built RLS and LMS block with and without libarmadillo and i realized that building without  libarmadillo gives almost two times higher throughput.
It seems arma::dot is slower than gnuradio fir_filter.
What is the reason for using arma::dot over gnuradio fir_filter?
And thank you very much for such awesome OOT blocks.

**Comment by karel** [comment]
Sorry for the delay. I couldn't verify the described behaviour. If anything, then using Armadillo results in a little bit faster code. I used the performance measurement tests provided in the [python folder](https://github.com/karel/gr-adapt/tree/master/python). The results seem to be consistent for all of the filters and with different amount of taps.

Initially Armadillo was used for everything but in order to get going with less dependencies, some blocks were ported to work with [libvolk](https://github.com/gnuradio/volk), which is required by GNU Radio anyway. I am not sure what results in the performance differences to be honest. Feel free to use the implementation, which is better performing on your system.
